name: Biweekly Release

on:
  # Run on the 1st and 15th of every month (approx. every 2 weeks)
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Ensure the token is not persisted to avoid credential issues when pushing changes.
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install && uv venv

      - name: Install GitPython
        run: uv pip install gitpython

      - name: Run biweekly_release.py
        run: uv run biweekly_release.py

      - name: Commit and push changes
        run: |
          # Configure git
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add pyproject.toml
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(ver): Bump version" && git push)
        env:
          # Use the GitHub token for authentication when pushing changes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
