name: Build docs

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install mkdocs-material git+https://github.com/devdrian/pdoc@reST_style_docstrings_support
          pip install -r requirements.txt
      - name: Generate API Documentation
        run: pdoc genshin --html -o "docs/pdoc" --force
      - name: Deploy docs
        run: mkdocs gh-deploy --force
